Pipelines:
 QCcontrol: ["fastqc", "abyss", "trimmomatic", "align"]
 assemble: ["abyss", "allpaths", "cabog",  "masurca", "soapdenovo", "spades", "trinity"]
 evaluete: ["align", "qaTools", "FRC"]
 align: []
Tools:
 fastqc:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/FastQC/fastqc
  options: [--threads,  "20" ,  --outdir,  fastqc]
 trimmomatic:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/Trimmomatic-0.32/trimmomatic-0.32.jar
  options: []
 abyss:
  bin: /usr/local/abyss-1.3.6/bin/
  options: []
 abyss_mergePairs:
  bin: /usr/local/abyss-1.3.6/bin/abyss-mergepairs
  options: []
 soapdenovo:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/SOAPdenovo2/SOAPdenovo-63mer
  options: [""]
 allpaths:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/allpathslg-47856/bin/bin/
  options: [""]
 bwa:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/bwa-0.7.5a/bwa
  options: ""
 picard:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/picard-tools-1.103/
  options: ""
 samtools:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/samtools-0.1.18/samtools
  options: ""
 qaTools:
  bin: /home/francesco.vezzi/DE_NOVO_PIPELINE/tools/qaTools/qaCompute
  options: ""
